[project]
name = "python-pyspark-demo"
version = "0.1.0"
description = "PySpark demo project"
requires-python = ">=3.13"
dependencies = [
    "pyspark",
    "pandas",
    "pyarrow",
    "jupyter",
]

[tool.uv]
dev-dependencies = []
